fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: debug-statements
    - id: detect-private-key
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
      exclude: .prob
    - id: trailing-whitespace
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
